version: "3.9"
services:
  database:
    restart: always
    image: "postgres:latest"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql